name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.1
      with:
        filename: 'build.zip'
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /home/runner/work/Demo-GitHubAction/Demo-GitHubAction/CMP186-WorkshopGitHubAction/bin/Debug/net5.0/publish/
